spring:
  application:
    name: micro-service-netflix-config-server
  profiles: configserver1
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/colddew/micro-service-config-repo

server:
  port: 8887

---

spring:
  application:
    name: micro-service-netflix-config-server
  profiles: configserver2
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/colddew/micro-service-config-repo

server:
  port: 8888